//
// Autogenerated by Natalie - Storyboard Generator Script.
// http://blog.krzyzanowskim.com
//

import UIKit
import AMScrollingNavbar

//MARK: - Storyboards

extension UIStoryboard {
    func instantiateViewController<T: UIViewController where T: IdentifiableProtocol>(type: T.Type) -> T? {
        let instance = type.init()
        if let identifier = instance.storyboardIdentifier {
            return self.instantiateViewControllerWithIdentifier(identifier) as? T
        }
        return nil
    }
}


protocol Storyboard {
    static var storyboard: UIStoryboard { get }
    static var identifier: String { get }
}

struct Storyboards {

    struct LaunchScreen: Storyboard {

        static let identifier = "LaunchScreen"

        static var storyboard: UIStoryboard {
            return UIStoryboard(name: self.identifier, bundle: nil)
        }

        static func instantiateInitialViewController() -> UIViewController {
            return self.storyboard.instantiateInitialViewController()!
        }

        static func instantiateViewControllerWithIdentifier(identifier: String) -> UIViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier(identifier)
        }

        static func instantiateViewController<T: UIViewController where T: IdentifiableProtocol>(type: T.Type) -> T? {
            return self.storyboard.instantiateViewController(type)
        }
    }

    struct Main: Storyboard {

        static let identifier = "Main"

        static var storyboard: UIStoryboard {
            return UIStoryboard(name: self.identifier, bundle: nil)
        }

        static func instantiateInitialViewController() -> UITabBarController {
            return self.storyboard.instantiateInitialViewController() as! UITabBarController
        }

        static func instantiateViewControllerWithIdentifier(identifier: String) -> UIViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier(identifier)
        }

        static func instantiateViewController<T: UIViewController where T: IdentifiableProtocol>(type: T.Type) -> T? {
            return self.storyboard.instantiateViewController(type)
        }

        static func instantiateGoodsTableViewController() -> BCOGoodsTableViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("GoodsTableViewController") as! BCOGoodsTableViewController
        }

        static func instantiateTipViewController() -> TipViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("TipViewController") as! TipViewController
        }
    }
}

//MARK: - ReusableKind
enum ReusableKind: String, CustomStringConvertible {
    case TableViewCell = "tableViewCell"
    case CollectionViewCell = "collectionViewCell"

    var description: String { return self.rawValue }
}

//MARK: - SegueKind
enum SegueKind: String, CustomStringConvertible {    
    case Relationship = "relationship" 
    case Show = "show"                 
    case Presentation = "presentation" 
    case Embed = "embed"               
    case Unwind = "unwind"             
    case Push = "push"                 
    case Modal = "modal"               
    case Popover = "popover"           
    case Replace = "replace"           
    case Custom = "custom"             

    var description: String { return self.rawValue } 
}

//MARK: - IdentifiableProtocol

public protocol IdentifiableProtocol: Equatable {
    var storyboardIdentifier: String? { get }
}

//MARK: - SegueProtocol

public protocol SegueProtocol {
    var identifier: String? { get }
}

public func ==<T: SegueProtocol, U: SegueProtocol>(lhs: T, rhs: U) -> Bool {
    return lhs.identifier == rhs.identifier
}

public func ~=<T: SegueProtocol, U: SegueProtocol>(lhs: T, rhs: U) -> Bool {
    return lhs.identifier == rhs.identifier
}

public func ==<T: SegueProtocol>(lhs: T, rhs: String) -> Bool {
    return lhs.identifier == rhs
}

public func ~=<T: SegueProtocol>(lhs: T, rhs: String) -> Bool {
    return lhs.identifier == rhs
}

public func ==<T: SegueProtocol>(lhs: String, rhs: T) -> Bool {
    return lhs == rhs.identifier
}

public func ~=<T: SegueProtocol>(lhs: String, rhs: T) -> Bool {
    return lhs == rhs.identifier
}

//MARK: - ReusableViewProtocol
public protocol ReusableViewProtocol: IdentifiableProtocol {
    var viewType: UIView.Type? { get }
}

public func ==<T: ReusableViewProtocol, U: ReusableViewProtocol>(lhs: T, rhs: U) -> Bool {
    return lhs.storyboardIdentifier == rhs.storyboardIdentifier
}

//MARK: - Protocol Implementation
extension UIStoryboardSegue: SegueProtocol {
}

extension UICollectionReusableView: ReusableViewProtocol {
    public var viewType: UIView.Type? { return self.dynamicType }
    public var storyboardIdentifier: String? { return self.reuseIdentifier }
}

extension UITableViewCell: ReusableViewProtocol {
    public var viewType: UIView.Type? { return self.dynamicType }
    public var storyboardIdentifier: String? { return self.reuseIdentifier }
}

//MARK: - UIViewController extension
extension UIViewController {
    func performSegue<T: SegueProtocol>(segue: T, sender: AnyObject?) {
        if let identifier = segue.identifier {
            performSegueWithIdentifier(identifier, sender: sender)
        }
    }

    func performSegue<T: SegueProtocol>(segue: T) {
        performSegue(segue, sender: nil)
    }
}

//MARK: - UICollectionView

extension UICollectionView {

    func dequeueReusableCell<T: ReusableViewProtocol>(reusable: T, forIndexPath: NSIndexPath!) -> UICollectionViewCell? {
        if let identifier = reusable.storyboardIdentifier {
            return dequeueReusableCellWithReuseIdentifier(identifier, forIndexPath: forIndexPath)
        }
        return nil
    }

    func registerReusableCell<T: ReusableViewProtocol>(reusable: T) {
        if let type = reusable.viewType, identifier = reusable.storyboardIdentifier {
            registerClass(type, forCellWithReuseIdentifier: identifier)
        }
    }

    func dequeueReusableSupplementaryViewOfKind<T: ReusableViewProtocol>(elementKind: String, withReusable reusable: T, forIndexPath: NSIndexPath!) -> UICollectionReusableView? {
        if let identifier = reusable.storyboardIdentifier {
            return dequeueReusableSupplementaryViewOfKind(elementKind, withReuseIdentifier: identifier, forIndexPath: forIndexPath)
        }
        return nil
    }

    func registerReusable<T: ReusableViewProtocol>(reusable: T, forSupplementaryViewOfKind elementKind: String) {
        if let type = reusable.viewType, identifier = reusable.storyboardIdentifier {
            registerClass(type, forSupplementaryViewOfKind: elementKind, withReuseIdentifier: identifier)
        }
    }
}
//MARK: - UITableView

extension UITableView {

    func dequeueReusableCell<T: ReusableViewProtocol>(reusable: T, forIndexPath: NSIndexPath!) -> UITableViewCell? {
        if let identifier = reusable.storyboardIdentifier {
            return dequeueReusableCellWithIdentifier(identifier, forIndexPath: forIndexPath)
        }
        return nil
    }

    func registerReusableCell<T: ReusableViewProtocol>(reusable: T) {
        if let type = reusable.viewType, identifier = reusable.storyboardIdentifier {
            registerClass(type, forCellReuseIdentifier: identifier)
        }
    }

    func dequeueReusableHeaderFooter<T: ReusableViewProtocol>(reusable: T) -> UITableViewHeaderFooterView? {
        if let identifier = reusable.storyboardIdentifier {
            return dequeueReusableHeaderFooterViewWithIdentifier(identifier)
        }
        return nil
    }

    func registerReusableHeaderFooter<T: ReusableViewProtocol>(reusable: T) {
        if let type = reusable.viewType, identifier = reusable.storyboardIdentifier {
             registerClass(type, forHeaderFooterViewReuseIdentifier: identifier)
        }
    }
}


//MARK: - ScrollingNavigationController

//MARK: - BCOHomeViewController
extension UIStoryboardSegue {
    func selection() -> BCOHomeViewController.Segue? {
        if let identifier = self.identifier {
            return BCOHomeViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension BCOHomeViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case ListControllerSegue = "ListControllerSegue"

        var kind: SegueKind? {
            switch (self) {
            case ListControllerSegue:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case ListControllerSegue:
                return BCOGoodsTableViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - BCOGoodsTableViewController
extension UIStoryboardSegue {
    func selection() -> BCOGoodsTableViewController.Segue? {
        if let identifier = self.identifier {
            return BCOGoodsTableViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension BCOGoodsTableViewController: IdentifiableProtocol { 
    var storyboardIdentifier: String? { return "GoodsTableViewController" }
    static var storyboardIdentifier: String? { return "GoodsTableViewController" }
}

extension BCOGoodsTableViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case ShowGoodsDealInfoSegue = "ShowGoodsDealInfoSegue"

        var kind: SegueKind? {
            switch (self) {
            case ShowGoodsDealInfoSegue:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case ShowGoodsDealInfoSegue:
                return BCOGoodsInfoViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}
extension BCOGoodsTableViewController { 

    enum Reusable: String, CustomStringConvertible, ReusableViewProtocol {
        case GoodsTableViewCellIdentifier = "GoodsTableViewCellIdentifier"

        var kind: ReusableKind? {
            switch (self) {
            case GoodsTableViewCellIdentifier:
                return ReusableKind(rawValue: "tableViewCell")
            }
        }

        var viewType: UIView.Type? {
            switch (self) {
            case GoodsTableViewCellIdentifier:
                return BCOGoodsTableViewCell.self
            }
        }

        var storyboardIdentifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}


//MARK: - BCOGoodsInfoViewController
extension UIStoryboardSegue {
    func selection() -> BCOGoodsInfoViewController.Segue? {
        if let identifier = self.identifier {
            return BCOGoodsInfoViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension BCOGoodsInfoViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case shareSegue = "shareSegue"

        var kind: SegueKind? {
            switch (self) {
            case shareSegue:
                return SegueKind(rawValue: "presentation")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case shareSegue:
                return BCOShareViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}
extension BCOGoodsInfoViewController { 

    enum Reusable: String, CustomStringConvertible, ReusableViewProtocol {
        case GoodsContentInfoCellIdentifier = "GoodsContentInfoCellIdentifier"

        var kind: ReusableKind? {
            switch (self) {
            case GoodsContentInfoCellIdentifier:
                return ReusableKind(rawValue: "tableViewCell")
            }
        }

        var viewType: UIView.Type? {
            switch (self) {
            case GoodsContentInfoCellIdentifier:
                return BCOGoodsInfoContentCell.self
            }
        }

        var storyboardIdentifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}


//MARK: - ScrollingNavigationController

//MARK: - BCOPersonTableViewController
extension UIStoryboardSegue {
    func selection() -> BCOPersonTableViewController.Segue? {
        if let identifier = self.identifier {
            return BCOPersonTableViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension BCOPersonTableViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case showFeedbackViewController = "showFeedbackViewController"

        var kind: SegueKind? {
            switch (self) {
            case showFeedbackViewController:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case showFeedbackViewController:
                return BCOFeedbackViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}
extension BCOPersonTableViewController { 

    enum Reusable: String, CustomStringConvertible, ReusableViewProtocol {
        case disclosureCellIdentifier = "disclosureCellIdentifier"

        var kind: ReusableKind? {
            switch (self) {
            case disclosureCellIdentifier:
                return ReusableKind(rawValue: "tableViewCell")
            }
        }

        var viewType: UIView.Type? {
            switch (self) {
            case disclosureCellIdentifier:
                return BCOPersonDetailCell.self
            }
        }

        var storyboardIdentifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}


//MARK: - BCOFeedbackViewController

//MARK: - BCOSearchViewController
extension BCOSearchViewController { 

    enum Reusable: String, CustomStringConvertible, ReusableViewProtocol {
        case SearchCellIdentifier = "SearchCellIdentifier"

        var kind: ReusableKind? {
            switch (self) {
            case SearchCellIdentifier:
                return ReusableKind(rawValue: "tableViewCell")
            }
        }

        var viewType: UIView.Type? {
            switch (self) {
            default:
                return nil
            }
        }

        var storyboardIdentifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}


//MARK: - BCOShareViewController

//MARK: - TipViewController
extension TipViewController: IdentifiableProtocol { 
    var storyboardIdentifier: String? { return "TipViewController" }
    static var storyboardIdentifier: String? { return "TipViewController" }
}

