source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'baicaio' do
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
	pod 'Alamofire', '~> 3.0'
	pod 'RealmSwift'
	pod 'YYText'
	pod 'AMScrollingNavbar', '~> 2.0.1'
	pod 'JBImageBrowserViewController'
	pod 'MonkeyKing', '~> 0.8'
	pod 'MJRefresh'
	pod 'FDFullscreenPopGesture', '1.1'
    pod 'JDStatusBarNotification'
end